
-- Add new columns to the employees table for the additional employee details
ALTER TABLE public.employees 
ADD COLUMN IF NOT EXISTS account_number TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS ifsc_code TEXT,
ADD COLUMN IF NOT EXISTS branch_name TEXT,
ADD COLUMN IF NOT EXISTS transfer_mode TEXT,
ADD COLUMN IF NOT EXISTS gross_salary NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS da_percentage NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS da_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS conveyance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS other_allowances NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS tea_allowance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS overtime_eligible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS late_deduction_eligible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pf_eligible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS esi_eligible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS shift_code TEXT,
ADD COLUMN IF NOT EXISTS contract_name TEXT,
ADD COLUMN IF NOT EXISTS mode_of_payment TEXT,
ADD COLUMN IF NOT EXISTS row_number INTEGER,
ADD COLUMN IF NOT EXISTS basic_salary_percentage NUMERIC DEFAULT 0;
